# Site settings
author: Lorena Cardenas
title: CLI process
header-img: img/home-bg.png
email: lorena@eunknown.org
copyright_name: Lorena Cardenas
description: > # this means to ignore newlines until "baseurl:"
  Stressing
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lorena57

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
